name: CI & CD

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "test/**"
      - "README.md"
      - "SECURITY.md"
      - "LICENSE"
      - "HISTORY.md"
      - "DOCUMENTATION.md"
      - "CONTRIBUTING.md"
      - ".sample.env"

jobs:
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Create environment
      run: |
        touch .env
        echo SSH = ${{ secrets.SSH }} >> .env
        echo NODE_ENV = ${{ secrets.NODE_ENV }} >> .env
        echo APP_NAME = ${{ secrets.APP_NAME }} >> .env
        echo EMAIL = ${{ secrets.EMAIL }} >> .env
        echo SITE = ${{ secrets.SITE }} >> .env
        echo DBUSER = ${{ secrets.DBUSER }} >> .env
        echo DBPASS = ${{ secrets.DBPASS }} >> .env
        echo DBNAME = ${{ secrets.DBNAME }} >> .env
        echo ADMIN_COL = ${{ secrets.ADMIN_COL }} >> .env
        echo INST_COL = ${{ secrets.INST_COL }} >> .env
        echo SESS_COL = ${{ secrets.SESS_COL }} >> .env
        echo DPASS = ${{ secrets.DPASS }} >> .env
        echo CPASS = ${{ secrets.CPASS }} >> .env
        echo PUSH_ID = ${{ secrets.PUSH_ID }} >> .env
        echo PUSH_KEY = ${{ secrets.PUSH_KEY }} >> .env
        echo PUSH_SEC = ${{ secrets.PUSH_SEC }} >> .env
        echo PUSH_CLUS = ${{ secrets.PUSH_CLUS }} >> .env
        echo MAIL_HOST = ${{ secrets.MAIL_HOST }} >> .env
        echo MAIL_PORT = ${{ secrets.MAIL_PORT }} >> .env
        echo MAILUSER = ${{ secrets.MAILUSER }} >> .env
        echo MAILPASS = ${{ secrets.MAILPASS }} >> .env
        echo MAILCIPHER = ${{ secrets.MAILCIPHER }} >> .env
        echo SESSPUBKEY = ${{ secrets.SESSPUBKEY }} >> .env
        echo SESSADMIN = ${{ secrets.SESSADMIN }} >> .env
        echo SESSTEACH = ${{ secrets.SESSTEACH }} >> .env
        echo SESSSTUD = ${{ secrets.SESSSTUD }} >> .env
        
    - name : Generate Config Keys
      run: npm run config
    - name: Install & Test
      run: |
        npm ci
        npm run build --if-present
        npm test
    - uses: akhileshns/heroku-deploy@v3.3.6
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
        heroku_email: ${{secrets.HEROKU_EMAIL_ID}}