name: CI

on:
  pull_request:
    branches: [ master ]
    paths-ignore: 
      - "test/**"
      - "README.md"
      - "SECURITY.md"
      - "LICENSE"
      - "HISTORY.md"
      - "DOCUMENTATION.md"
      - "CONTRIBUTING.md"
      - "sample.env"

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Create environment
      run: |
        touch .env
        echo SSH = ${{ secrets.SSH }} >> .env
        echo NODE_ENV = ${{ secrets.NODE_ENV }} >> .env
    - name: Install & Test
      run: |
        npm ci
        npm run build --if-present
        npm test